# If you come from bash you might have to change your $PATH.
# export PATH=$HOME/bin:/usr/local/bin:$PATH

# Path to your oh-my-zsh installation.
export ZSH=~/.oh-my-zsh

# Set name of the theme to load. Optionally, if you set this to "random"
# it'll load a random theme each time that oh-my-zsh is loaded.
# See https://github.com/robbyrussell/oh-my-zsh/wiki/Themes
ZSH_THEME="robbyrussell"

# Uncomment the following line to use case-sensitive completion.
# CASE_SENSITIVE="true"

# Uncomment the following line to use hyphen-insensitive completion. Case
# sensitive completion must be off. _ and - will be interchangeable.
# HYPHEN_INSENSITIVE="true"

# Uncomment the following line to disable bi-weekly auto-update checks.
# DISABLE_AUTO_UPDATE="true"

# Uncomment the following line to change how often to auto-update (in days).
# export UPDATE_ZSH_DAYS=13

# Uncomment the following line to disable colors in ls.
# DISABLE_LS_COLORS="true"

# Uncomment the following line to disable auto-setting terminal title.
# DISABLE_AUTO_TITLE="true"

# Uncomment the following line to enable command auto-correction.
# ENABLE_CORRECTION="true"

# Uncomment the following line to display red dots whilst waiting for completion.
# COMPLETION_WAITING_DOTS="true"

# Uncomment the following line if you want to disable marking untracked files
# under VCS as dirty. This makes repository status check for large repositories
# much, much faster.
# DISABLE_UNTRACKED_FILES_DIRTY="true"

# Uncomment the following line if you want to change the command execution time
# stamp shown in the history command output.
# The optional three formats: "mm/dd/yyyy"|"dd.mm.yyyy"|"yyyy-mm-dd"
# HIST_STAMPS="mm/dd/yyyy"

# Would you like to use another custom folder than $ZSH/custom?
# ZSH_CUSTOM=/path/to/new-custom-folder

# Which plugins would you like to load? (plugins can be found in ~/.oh-my-zsh/plugins/*)
# Custom plugins may be added to ~/.oh-my-zsh/custom/plugins/
# Example format: plugins=(rails git textmate ruby lighthouse)
# Add wisely, as too many plugins slow down shell startup.
plugins=(git)

source $ZSH/oh-my-zsh.sh

# User configuration

# export MANPATH="/usr/local/man:$M3ANPATH"

# You may need to manually set your language environment
# export LANG=en_US.UTF-8

# Preferred editor for local and remote sessions
# if [[ -n $SSH_CONNECTION ]]; then
#   export EDITOR='vim'
# else
#   export EDITOR='mvim'
# fi

# Compilation flags
# export ARCHFLAGS="-arch x86_64"

# ssh
# export SSH_KEY_PATH="~/.ssh/rsa_id"

# Set personal aliases, overriding those provided by oh-my-zsh libs,
# plugins, and themes. Aliases can be placed here, though oh-my-zsh
# users are encouraged to define aliases within the ZSH_CUSTOM folder.
# For a full list of active aliases, run `alias`.
#
# Example aliases
# alias zshconfig="mate ~/.zshrc"
# alias ohmyzsh="mate ~/.oh-my-zsh"

rmPath() {
  local tgt=${1}
  PATH=$(printf %s $PATH | awk -v RS=: -v ORS=: 'BEGIN { t="^'${tgt}'$"} $1!~t { print }')
}

addPath() {
  local tgt=${1}
  if [[ -d "${tgt}" ]]; then
    rmPath ${tgt}
    PATH="${tgt}:$PATH"
  fi
}

osource() {
  local tgt=${1}
  if [ -f "${tgt}" ]; then
    source "${tgt}"
  fi
}

## misc binaries
mkdir -p "$HOME/bin"
addPath "$HOME/bin"
mkdir -p "$HOME/go/bin"
addPath "$HOME/go/bin"

## homebrew
addPath "/usr/local/sbin"
addPath "/usr/local/opt/gnu-tar/libexec/gnubin"
addPath "/usr/local/opt/python/libexec/bin"

## rbenv
addPath "$HOME/.rbenv/bin"
if type rbenv >>&/dev/null; then
  eval "$(rbenv init -)"
fi

## heroku (via homebrew)
if [ -e /usr/local/bin/heroku ]; then
  alias heroku='PATH="/usr/local/opt/python@2/bin:$PATH" /usr/local/bin/heroku'
  alias h='PATH="/usr/local/opt/python@2/bin:$PATH" /usr/local/bin/heroku'
fi

## codeql
if [ -d /usr/local/codeql ]; then
  addPath "/usr/local/codeql"
fi

## Misc 
unalias gb

## Work specific
if [ -f ~/.zshrc.work ]; then source ~/.zshrc.work; fi

## GPG
# https://github.com/pstadler/keybase-gpg-github#optional-setting-up-tty
# https://github.com/keybase/keybase-issues/issues/2798
GPG_TTY=$(tty)
export GPG_TTY

## Google Cloud
osource '/usr/local/Caskroom/google-cloud-sdk/latest/google-cloud-sdk/path.zsh.inc'
osource '/usr/local/Caskroom/google-cloud-sdk/latest/google-cloud-sdk/completion.zsh.inc'

## One password
alias opm='eval $(op signin mullers)'
alias opg='eval $(op signin gobridge)'

## Direnv
eval "$(direnv hook zsh)"