# If you come from bash you might have to change your $PATH.
# export PATH=$HOME/bin:/usr/local/bin:$PATH

# Path to your oh-my-zsh installation.
export ZSH=~/.oh-my-zsh

# Set name of the theme to load. Optionally, if you set this to "random"
# it'll load a random theme each time that oh-my-zsh is loaded.
# See https://github.com/robbyrussell/oh-my-zsh/wiki/Themes
ZSH_THEME="robbyrussell"

# Uncomment the following line to use case-sensitive completion.
# CASE_SENSITIVE="true"

# Uncomment the following line to use hyphen-insensitive completion. Case
# sensitive completion must be off. _ and - will be interchangeable.
# HYPHEN_INSENSITIVE="true"

# Uncomment the following line to disable bi-weekly auto-update checks.
# DISABLE_AUTO_UPDATE="true"

# Uncomment the following line to change how often to auto-update (in days).
# export UPDATE_ZSH_DAYS=13

# Uncomment the following line to disable colors in ls.
# DISABLE_LS_COLORS="true"

# Uncomment the following line to disable auto-setting terminal title.
# DISABLE_AUTO_TITLE="true"

# Uncomment the following line to enable command auto-correction.
# ENABLE_CORRECTION="true"

# Uncomment the following line to display red dots whilst waiting for completion.
# COMPLETION_WAITING_DOTS="true"

# Uncomment the following line if you want to disable marking untracked files
# under VCS as dirty. This makes repository status check for large repositories
# much, much faster.
# DISABLE_UNTRACKED_FILES_DIRTY="true"

# Uncomment the following line if you want to change the command execution time
# stamp shown in the history command output.
# The optional three formats: "mm/dd/yyyy"|"dd.mm.yyyy"|"yyyy-mm-dd"
# HIST_STAMPS="mm/dd/yyyy"

# Would you like to use another custom folder than $ZSH/custom?
# ZSH_CUSTOM=/path/to/new-custom-folder

# Which plugins would you like to load? (plugins can be found in ~/.oh-my-zsh/plugins/*)
# Custom plugins may be added to ~/.oh-my-zsh/custom/plugins/
# Example format: plugins=(rails git textmate ruby lighthouse)
# Add wisely, as too many plugins slow down shell startup.
plugins=(git)

source $ZSH/oh-my-zsh.sh

# User configuration

# export MANPATH="/usr/local/man:$M3ANPATH"

# You may need to manually set your language environment
# export LANG=en_US.UTF-8

# Preferred editor for local and remote sessions
# if [[ -n $SSH_CONNECTION ]]; then
#   export EDITOR='vim'
# else
#   export EDITOR='mvim'
# fi

# Compilation flags
# export ARCHFLAGS="-arch x86_64"

# ssh
# export SSH_KEY_PATH="~/.ssh/rsa_id"

# Set personal aliases, overriding those provided by oh-my-zsh libs,
# plugins, and themes. Aliases can be placed here, though oh-my-zsh
# users are encouraged to define aliases within the ZSH_CUSTOM folder.
# For a full list of active aliases, run `alias`.
#
# Example aliases
# alias zshconfig="mate ~/.zshrc"
# alias ohmyzsh="mate ~/.oh-my-zsh"

rmPath() {
  local tgt=${1}
  PATH=$(printf %s $PATH | awk -v RS=: -v ORS=: 'BEGIN { t="^'${tgt}'$"} $1!~t { print }')
}

addPath() {
  local tgt=${1}
  if [[ -d "${tgt}" ]]; then
    rmPath ${tgt}
    PATH="${tgt}:$PATH"
  fi
}

## -- Go version management
## Change this if you want to use a different directory
## $HOME/sdk is compatible with 
export gosdk=$HOME/sdk

## Current go version. Blank == none. Defaults to the highest version in $gosdk
export goversion=$(if [[ -d ${gosdk} ]]; then
ls ${gosdk} | awk '
BEGIN { v = 0 }
{
    n = split($1,parts,".")
    num = sprintf("%0.3d%0.3d%0.3d",substr($1,3,1), parts[2], parts[3])
    if (num > v) {
        v = num
    }
}
END {
    if (v == 0) {
      exit
    }
    maj = substr(v,0,3)
    min = substr(v,4,3)
    patch = substr(v,7,3)
    printf "go%d.%d", maj, min
    if (patch > "000") {
        printf ".%d", patch
    }
    printf "\n"
}'
fi)

## downloadGoVersion <version|latest>
## downloads to $gosdk
## Pass "latest" to {re,}download the latest version of go
## Pass a specific version to {re,}download it.
## Assumes version starts with 'go'. Specify 'go1.16.2', not '1.16.2'
## Uses $HOME/sdk/.dl
downloadGoVersion() {
  local gv="${1}"
  if [[ -z ${gv} ]]; then
    echo "downloagGoVersion <version|latest>"
    return 1
  fi

  if [[ "${gv}" == "latest" ]]; then
    gv=$(curl -s https://golang.org/VERSION\?m=text)
  fi

  local arch=$(uname -m)
  if [[ "${arch}" == "x86_64" ]]; then
    arch="amd64"
  fi
  local sys=$(uname -s)
  local sdk=$gosdk
  local gdt=${sdk}/.dl
  local gvd=${sdk}/${gv}
  mkdir -p ${gdt}
  if [[ -d ${gvd} ]]; then
    rm -rf ${gvd}
  fi
  local url="https://dl.google.com/go/${gv}.${sys:l}-${arch}.tar.gz"
  curl -s -S --fail ${url} | tar zxf - -C ${gdt}
  local r=${pipestatus[1]}
  if [[ ${r} != 0 ]]; then
    >&2 echo "requested url: ${url}"
    >&2 echo ""
    rm -rf ${gdt}
    return ${r}
  fi
  mv ${gdt}/go ${gvd} && echo "${gv} downloaded"
  rm -rf ${gdt}
}

setGoVersion() {
  local ver="${1}"
  if [[ -z "${ver}" ]]; then
    echo "setGoVersion <version|latest>"
    return 1
  fi
  if [[ ${ver} == "latest" ]]; then
    ver=$(curl -s https://golang.org/VERSION\?m=text)
  fi

  local sdk="${gosdk}"
  local gd="${sdk}/${ver}"
  if [[ ! -d ${gd} ]]; then
    echo "${ver} not found locally, downloading to ${gd}"
    local downloaded=$(downloadGoVersion ${ver})
    if [[ -z "${downloaded}" ]]; then
      >&2 echo "Unable to install ${ver}"

      local sys=$(uname -s)
      local arch=$(uname -m)
      if [[ "${arch}" == "x86_64" ]]; then
        arch="amd64"
      fi
      local agv=$(curl -s https://golang.org/dl/\?mode\=json\&include\=all | jq '[ .[] | .files |= map(select(.kind == "archive" and .os == "'${sys:l}'" and .arch == "'${arch}'")) | select((.files | length) == 1)]' )
      if [[ ${ver} != "latest" && -z "$(echo ${agv} | jq -r '.[] | select(.version == "'${ver}'")')" ]]; then
        >&2 echo ""
        >&2 echo "${ver} isn't available for ${sys:l}/${arch}"
      fi
      if [[ ! -z ${goversion} ]]; then
        >&2 echo ""
        >&2 echo "Current Local Go Version: ${goversion}"
      fi
      >&2 echo ""
      >&2 echo -n "Local versions available: "
      >&2 echo $(ls ${sdk})
      >&2 echo ""
      >&2 echo "Latest version: $(echo $agv | jq -r '.[0].version')"
      >&2 echo ""
      >&2 echo -n "All versions available for OS ($sys) & ARCH ($arch): "
      >&2 echo $(echo $agv | jq -r '.[] | .version')
      >&2 echo ""
      return ${rv}
    fi
    echo "Success!"
    ver=$(echo $downloaded | awk '{ print $2 }')
  fi

  local gbd="${gd}/bin"
  # delete any go sdk path items
  PATH="$(printf %s $PATH | awk -v RS=: -v ORS=: 'BEGIN { t="^'$HOME'/sdk/go[0-9]\.[0-9]{1,2}(\.[0-9]{1,2}){1,2}/bin$" } $1!~t { print }')"
  addPath ${gbd}
  goversion=${ver}
  echo "set $(go version | awk '{ print $1, $2, "to", $3, "on", $4 }')"
}

rmGoVersion() {
  local ver="${1}"
  local gd="${gosdk}/${ver}"

  if [[ -d ${gd} ]]; then
    rm -rf ${gd} && echo "${ver} removed" && return
  fi
  echo "${ver} does not exist locally"
  return 1
}

mkdir -p ${gosdk}
if [[ -z "${goversion}" ]]; then
  echo -e "No Go SDK installed. Install the latest by running: setGoVersion latest"
else
  setGoVersion ${goversion}
fi
## / - Go version management

osource() {
  local tgt=${1}
  if [ -f "${tgt}" ]; then
    source "${tgt}"
  fi
}

## homebrew
addPath "/usr/local/sbin"
addPath "/usr/local/opt/gnu-tar/libexec/gnubin"
addPath "/usr/local/opt/python/libexec/bin"

## rbenv
addPath "$HOME/.rbenv/bin"
if type rbenv >>&/dev/null; then
  eval "$(rbenv init -)"
fi

## heroku (via homebrew)
if [ -e /usr/local/bin/heroku ]; then
  alias heroku='PATH="/usr/local/opt/python@2/bin:$PATH" /usr/local/bin/heroku'
  alias h='PATH="/usr/local/opt/python@2/bin:$PATH" /usr/local/bin/heroku'
fi

## codeql
if [ -d /usr/local/codeql ]; then
  addPath "/usr/local/codeql"
fi

## Misc 
unalias gb
alias gcdr="cd $(git rev-parse --show-toplevel)"

## Work specific
if [ -f ~/.zshrc.work ]; then source ~/.zshrc.work; fi

## GPG
# https://github.com/pstadler/keybase-gpg-github#optional-setting-up-tty
# https://github.com/keybase/keybase-issues/issues/2798
GPG_TTY=$(tty)
export GPG_TTY

## Google Cloud
osource '/usr/local/Caskroom/google-cloud-sdk/latest/google-cloud-sdk/path.zsh.inc'
osource '/usr/local/Caskroom/google-cloud-sdk/latest/google-cloud-sdk/completion.zsh.inc'

## One password
alias opm='eval $(op signin mullers)'
alias opg='eval $(op signin gobridge)'